SELECT * FROM USERTABLE;
SELECT * FROM JOINTABLE;
SELECT * FROM JOINCOMMENT;
SELECT * FROM APPLYTABLE;
SELECT * FROM CITYTABLE;
SELECT * FROM HOBBYTABLE;
SELECT * FROM BOARDTABLE;
SELECT * FROM BOARDCOMMENT;
SELECT * FROM MESSAGETABLE;

