DROP TABLE NOTICETABLE;
DROP SEQUENCE NOTICETABLE_SEQ;

DROP TABLE ADMINTABLE;

DROP TABLE CITYTABLE;
DROP TABLE HOBBYTABLE;

DROP TABLE BOARDCOMMENT;
DROP SEQUENCE BOARDCOMMENT_SEQ;
DROP TABLE BOARDTABLE;
DROP SEQUENCE BOARDTABLE_SEQ;

DROP TABLE APPLYTABLE;

DROP TABLE MESSAGETABLE;
DROP SEQUENCE MESSAGETABLE_SEQ;
DROP TABLE JOINCOMMENT;
DROP SEQUENCE JOINCOMMENT_SEQ;
DROP TABLE JOINTABLE;
DROP SEQUENCE JOINTABLE_SEQ;

DROP TABLE USERTABLE;