SELECT * FROM USERTABLE;
DESC USERTABLE;

SELECT * FROM ADMINTABLE;
DESC ADMINTABLE;

SELECT * FROM JOINTABLE ORDER BY j_date DESC;
DESC JOINTABLE;

SELECT * FROM BOARDTABLE;
DESC BOARDTABLE;

SELECT * FROM NOTICETABLE;
DESC NOTICETABLE;

SELECT * FROM  BOARDCOMMENT ORDER BY bc_date;
DESC BOARDCOMMENT;

SELECT * FROM  JOINCOMMENT ORDER BY jc_date;
DESC JOINCOMMENT;
    
SELECT * FROM APPLYTABLE;
DESC APPLYTABLE;

-- ap_bidx 랑 j_idx 같은 사람 출력
SELECT j_idx, j_nickname, j_title, j_date, j_count 
    FROM JOINTABLE 
    WHERE j_id = 'aaaaaa';

DESC APPLYTABLE;