-- FK로 DROP은 거꾸로 실행
DROP TABLE APPLYTABLE;
DROP TABLE JOINCOMMENT;
DROP TABLE BOARDCOMMENT;
DROP TABLE NOTICETABLE;
DROP TABLE BOARDTABLE;
DROP TABLE JOINTABLE;
DROP TABLE ADMINTABLE;
DROP TABLE USERTABLE;
DROP SEQUENCE APPLYTABLE_SEQ;
DROP SEQUENCE JOINCOMMENT_SEQ;
DROP SEQUENCE BOARDCOMMENT_SEQ;
DROP SEQUENCE NOTICETABLE_SEQ;
DROP SEQUENCE BOARDTABLE_SEQ;
DROP SEQUENCE JOINTABLE_SEQ;

